sudo: required

language: node_js

node_js:
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH:./node_modules/.bin"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install
  - yarn run prepublish
  - yarn test
  - yarn run demo

addons:
  firefox: "52.0"

cache:
  yarn: true
